### ISSUE TITLE
Iterate on generate artifact

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1240]
## 🚀 Feature

We extracted the logic to generate artifacts to a pure function on #1222. 

Future tasks to be done are:

- [ ] Add test coverage for the new unction

- [ ] Review an efficient and immutable way to include information for `deprecatedFunctions` between versions on the generated JSON object. For reference: https://github.com/aragon/aragon-cli/issues/450 and https://github.com/aragon/aragon.js/pull/349

- [ ] Add deprecatedFunctions logic on artifact generation #1440 

- [ ] Check app's abi does not have conflicts with AppProxy's abi #1303

- [ ] Avoid fetching full IPFS blob of package to check if version bump is possible #838 

- [ ] Make sure we are using the same ipfs hash across environments #1277 

- [ ] Add warning if aragon app solidity code initializes any global variable #26
