### ISSUE TITLE
[EPIC] Improve Aragen

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1272]
We should address the following issues:

- [ ] https://github.com/aragon/aragen/issues/97

- [ ] https://github.com/aragon/aragen/issues/99

- [ ] https://github.com/aragon/aragen/issues/98
