### ISSUE TITLE
Support subdomains in Buidler plugin

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1406]
See https://github.com/aragon/buidler-aragon/pull/10#issuecomment-583417617

### Tasks
- [ ] Dynamically deploy subdomains when needed, so that users can specify ens names like <name>.<something>.aragonpm.eth
- [ ] Make sure that we still do some validation tho.
- [ ] Remove other environments from the arapp.json file, to keep things minimal.
