### ISSUE TITLE
Improve solidity-extractor logic

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1463]
There were several issues around improvements of the solidity extractor logic. This issue is to group those and keep track on the progress around this topic.

TODO:

- [ ] Wrong generated signature for array of contracts parameters #931

- [ ] Ignore @notice strings on modifiers #427

- [ ] Fails on fallback function #283
