### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#364]
close #349 , #348 

The current documentation is not up to date and there is a more and more demand to include new changes. Also there are lot of information distribute between forum.aragon (like [this great guide](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507) made by Luke, similar questions answered in aragon.chat, [boilerplates readme](https://github.com/aragon/aragon-react-boilerplate/blob/master/README.md) and hack.aragon.

This is not a please experience for a dev starting with aragonCLI so this issue will include a thoughtful review of all the documentation currently available in all places aiming to unify it in hack.aragon. At the same time, it make sense to restructure documentation on hack.aragon to include:
- Quick start / Overview / Introduction
- Guides around specific subjects (e.g.: Publish to different environments, Using a different Ethereum account, Propagating content, etc), similar to [this](https://github.com/aragon/aragon-react-boilerplate#publish)
- FAQ section. We have [this](https://hack.aragon.org/docs/cli-usage.html#troubleshooting-faq) currently, but it should be it's own section and much more elaborate (If there is a recurring question on #dev-help we will add it there)

TODO:

- [x] Update exiting documentation

- [x] [Related issues](https://github.com/aragon/aragon-cli/issues?q=is%3Aissue+is%3Aopen+label%3Adocs)

- [x] Restructure documentation on hack.aragon

Note: I reported this issue here to been able to track it in our milestones

**Comment by 0xGabi** [comment]
Achieved in https://github.com/aragon/hack/pull/99
