### ISSUE TITLE
Testing roadmap

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#417]
Steady process with the objective of improve testing across the repo. The tests will follow the [testing documentation](https://github.com/aragon/aragon-cli/blob/master/docs-internal/Testing.md). Below is a tentative roadmap.

- [x] `create-aragon-app`

- [x] `ipfs-cmds` #415

- [ ] `utils-cmds` (devchain, deploy and contracts)

- [x] `apm-cmds`

- [ ] `dao-cmds`

  - [ ] `token-cmds`

  - [ ] `acl-cmds`
 
- [x] `utils-cmds` (run)

**Comment by 0xGabi** [comment]
Closed for #602
