### ISSUE TITLE
Low-hanging fruit changes

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#827]
## List of available low-hanging fruit changes

- [x] Import ABIs from `@aragon/os` and `@aragon/id` instead of hardcoding them #818 

- [x] create-aragon-app: Interactive list of boilerplates to choose from #812 

- [x] `aragon contracts` output cut off #783

- [x] Better error message when we detect a cycle dependency #780

- [ ] create `~/.aragon` on instalation with boilerplate key files #777

- [ ] Detect if IPFS version is outdated #774 

- [ ] IPFS init: checking whether `.ipfs` exists is brittle (e.g. when IPFS is installed via SNAP) #744

- [ ] Merge AppProxy's ABI into artifact.abi #659 

- [x] Print the version of the CLI when using --debug #634

- [ ] Limit deploying to http only if on a localhost server #573 

- [x] Setup CI on Windows machines #527 

- [ ] Detect IPFS or HTTP server wasn't running and warn before fetching artifacts #509

- [ ] Ignore @notice strings on modifiers #427 

- [ ] Warn about default environments and arapp.json #373 

- [x] aragon dao foo ... doesn't error #372 

- [ ] Analyze role and role params against actual contract usage #370 

- [ ] `dao exec`, `dao act`: fix support for string types in function arguments #369 

- [ ] Minor issues on windows #367 

- [x] Don't use already open port #333 

- [ ] apm publish minor/patch add better error message #310 

- [ ] dao install needs a better error message if permission is missing #309 

- [ ] aragon run add error messaging if you try to use a network other than local rpc #308 

- [ ] `aragon dao install` fails with "replacement transaction underpriced" #306 

- [ ] Solidity parser fails on fallback function #283 

- [x] Wrong options provided by `--help` for subcommands #282

- [x] aragon run should warn if an existing ganache-cli is running (or not set up correctly) #160

- [ ] wrapper doesn't re-download if initial download attempt times out #139 

- [ ] 'aragon dao': Improve table readability by allowing to filter columns #85 

- [x] create-aragon-app should not be recursively looking up the path for a truffle.js #78 

- [x] Generated artifact.json does not include public constants #56 

- [ ] publish: Add warning if aragon app solidity code initializes any global variable #26

**Comment by macor161** [comment]
Great summary! Thanks a lot @0xGabi

**Comment by 0xGabi** [comment]
This issue serve it's purpose of organizing current low-hanging fruit. Going forward we are using Sprint planing an a much better tag system that already track reminded issues
