### ISSUE TITLE
Refactor entire codebase for separating logic from commands

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#858]
## Planning

Planning document, [here.](https://docs.google.com/document/d/14wqx_hEif6M_8g1fqNctdsVSbjVN7InYblr04wZ7CyQ/edit#heading=h.roiaaczav1ux)

Following @0x6431346e's [proposal on how to separate logic from commands](https://github.com/aragon/aragon-cli/pull/856), we're ready to start implementing this in the code.

## Preliminary tasks
- [x] Finish merging outstanding PRs: https://github.com/aragon/aragon-cli/issues/853
- [x] Finish setting up branching strategy for refactors: https://github.com/aragon/aragon-cli/issues/851
- [x] Rebase #856 to master so that it assimilates all the outstanding PR changes
- [x] Merge #856 to the new develop branch

Having completed these preliminary tasks, we're ready to start implementing the refactor, with the following considerations:
* Logic should be extracted to the `lib/` folder following the `token new` command's example (#856).
* Unit tests should be added to all extracted logic, again following the example.
* We shouldn't worry about end-to-end tests for now, but do try to test commands involved with what you're changing before pushing changes.
* Extracted logic should be 100% agnostic, and at most provide updates to the commands using them via callback handlers.
* We can start picking off commands to refactor from the list below, and making independent PRs to the develop branch. Once you pick an issue, add your name next to the item in the list below, or ask one of the repo maintainers to add it for you.

## Refactor based on commands
- [ ] ⬇️ :mountain: **[ Dev: @dapplion , Reviewers: ? ]** start command
- [x] apm commands
  - [x] **[ Dev: @ajsantander, Reviewers: @0xGabi ]** apm info
  - [x] **[ Dev: @ajsantander, Reviewers: @0xGabi, @macor161  ]** apm extract-functions
  - [x] **[ Dev: @ajsantander, Reviewers: @0xGabi, @dapplion  ]** apm versions
  - [x] **[ Dev: @ajsantander, Reviewers: @0xGabi, @macor161  ]** apm packages
- [x] **[ Dev: @dapplion, Reviewers: @0xGabi,  ]** deploy command
- [ ]  ⬇️ :mountain: **[ Dev: @macor161, Reviewers: ? ]** devchain command
- [x]  init command (Deprecated, I'll merge a commit that remove this instead)
- [x] middlewares
  - [x] **[ Dev: @0x6431346e, Reviewers: @macor161  ]** reporter **Ready to be merged: #965**
  - [x] **[ Dev: @dapplion , Reviewers: ? ]** manifest
  - [x] **[ Dev: @dapplion , Reviewers: ? ]** module
  - [x] **[ Dev: @dapplion , Reviewers: ? ]** environment
- [x] **[ Dev: @0x6431346e, Reviewers: @0xGabi , @dapplion ]** ipfs command
  - [x] ipfs start command
  - [x] ipfs install command
  - [x] ipfs uninstall command
  - [x] ipfs propagate command
  - [x] ipfs status command
  - [x] ipfs view command
- [ ] dao commands 
  - [ ] **[ Dev: @macor161, Reviewers: ?  ]** dao new command **Ready to be merged: #955**
  - [ ] ⬇️ :mountain: **[ Dev: @macor161, Reviewers: ? ]** dao act command
  - [ ] **[ Dev: @macor161, Reviewers: @0xGabi ]** dao apps command **Ready to be merged: #955**
  - [x] **[ Dev: @macor161, Reviewers: @0xGabi ]** dao exec command
  - [x] **[ Dev: @macor161, Reviewers: @0xGabi  ]** dao id-assign command
  - [x]  **[ Dev: @dapplion , Reviewers: ? ]** dao install command 
  - [x]  **[ Dev: @ dapplion , Reviewers: ? ]** dao upgrade command 
  - [x] **[ Dev: @0x6431346e, Reviewers: mcormier, ? ]** token commands
    - [x] token new command
    - [x] token change-controller command
  - [x] **[ Dev: @dapplion, Reviewers: @0xGabi, @macor161 ]** acl commands
    - [x] acl create command
    - [x] acl grant command
    - [x] acl remove-manager command
    - [x] acl revoke command
    - [x] acl set-manager command
    - [x] acl view command
- [x] **[ Dev: @dapplion, Reviewers: ? ]** contracts command

## After refactoring the commands
- [ ] **[ Dev: , Reviewers:   ]** apm publish
- [ ] **[ Dev: , Reviewers: ? ]** run command
- [ ] **[ Dev: ?, Reviewers: ? ]dao commands / utils
- [ ] Full review to see if there is still any logic within commands
- [ ] Sanitize utilities, making sure they are all bundled nicely in the `lib/` folder
- [ ] Review unit test coverage in `lib/`
- [ ] Add test on other parts of the codebase (e.g. utils)
- [ ] Improve how we handle`listr` context variables: https://github.com/aragonone/product/issues/222#issuecomment-548961338
- [ ] Windows CI
- [ ] CI for boilerplates, tutorials
- [ ] Review linter configuration and rules (@dapplion)
- [ ] Declare yargs commands explicitly instead of with `commandDir` and order by priority / usage

## Suggested next steps
- [ ] Create an issue for moving the `lib/` folder to a new package so that it can be bootstrapped to use Typescript
- [ ] Create an issue to port this lib package to Typescript

**Comment by 0xGabi** [comment]
@dapplion feel free to choose from the list as well☝️

**Comment by dapplion** [comment]
@0xGabi I'll start with **acl commands** if it's okay.

**Comment by dapplion** [comment]
I'll take the **deploy command** too

**Comment by ottodevs** [comment]
I can take `run` and `contract` commands if they are not taken, and also I would be fine being added as a reviewer for any opened PR

**Comment by dapplion** [comment]
@0xGabi I can tackle the rest of the middleware tasks.

**Comment by dapplion** [comment]
@ajsantander @0xGabi  You can mark the remaining middlewares as downhill

**Comment by 0xGabi** [comment]
I consider this issue done. We tackle most of the tasks and those still not done were decided to address on #947 or move to the developer flow.
