### ISSUE TITLE
Refactor codebase for robustness

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#947]
## 🔮 Planning

1. Follow @0x6431346e's [proposal on how to add integration tests](https://github.com/aragon/aragon-cli/pull/904) and aim for **50-60%** of coverage by the end of the refactor. Focusing on the `/lib` folder, the logic.

2. Implement [common mocks](https://github.com/aragon/aragon-cli/pull/945) and patterns (e.g. `progressHandler`).

3. Move code logic away from the `wrapper` unless it’s absolutely necessary.

## Preliminary tasks

Diagram with current progress: [here](https://drive.google.com/file/d/1jqbzTfqwdLmd4lHOzzXpCoScRMpYNdHQ/view?usp=sharing)

- **Blue**: DONE
- **Yellow**: TODO
- **Red**: WIP

#### Review and merge
  - [x] https://github.com/aragon/aragon-cli/pull/912
  - [x] https://github.com/aragon/aragon-cli/pull/871
  - [x] https://github.com/aragon/aragon-cli/pull/946

#### Finish WIP on
  - [x] `reporter` middleware #965
  - [x] `token change-controller` #972
  - [x] https://github.com/aragon/aragon-cli/pull/874 
    - [x] `dao new` #955
    - [x] `dao act` #970 
    - [x] `dao apps` #955
  - [ ] `aragon start` #974
  - [ ] `aragon devchain` 
  - [ ] `aragon contracts` #971 
  - [ ] Add IPFS to integration tests #951

### Pre-work discussions:

- [ ] How to incorporate complex side effects into the `/lib` folder? These include: 
  - installing, configuring and running binaries: `ipfs`, `devchain` 
  - Usage of `npm`
  - File system manipulation
- [ ] How to test these complex side effects?

### Logic units that involved several commands

- [ ] `amp publish` **[ Dev: , Reviewers:  ]**  WIP PR: https://github.com/aragon/aragon-cli/pull/906 (Includes plan for iteration 2)
- [ ] `run` **[ Dev: , Reviewers:  ]** 
- [ ] `don't use process.exit` **[ Dev: , Reviewers:  ]**  proposal issue https://github.com/aragon/aragon-cli/issues/948
- [ ] `dao commands utils` **[ Dev: , Reviewers:  ]**
- [ ] `execHandler` **[ Dev: , Reviewers:  ]** 
- [ ] `Initialize utilities on middleware` (ipfs, wrapper, apm and providers) and sanitize options **[ Dev: , Reviewers:  ]** 
- [ ] `extract shared logic from dao install / upgrade` **[ Dev: , Reviewers:  ]** 

### Add integration tests to the whole codebase

WIP integration tests https://github.com/aragon/aragon-cli/pull/952

- [ ] `middlewares` **[ Dev: , Reviewers:  ]**
- [ ] `start` **[ Dev: @0xGabi, Reviewers: ? ]** 
- [ ] `apm` **[ Dev: , Reviewers:  ]**
- [ ] `deploy` **[ Dev: , Reviewers:  ]**
- [ ] `devchain` **[ Dev: , Reviewers:  ]**
- [ ] `ipfs` **[ Dev: , Reviewers:  ]**
- [ ] `dao` **[ Dev: , Reviewers:  ]**
- [ ] `token ` **[ Dev: , Reviewers:  ]**
- [ ] `acl ` **[ Dev: , Reviewers:  ]**
- [ ] `contracts ` **[ Dev: , Reviewers:  ]**
- [ ] `extract-functions ` **[ Dev: , Reviewers:  ]**

#### Conventions
- global variables better than ctx
- code in `exports.task` is merged into `exports.handler` to make it explicit that this task is not used by any other module
 - separate disk I/O, cli-specific errors and pure logic

#### Relevant team feedback

- Write tests for `acl.js`
- Write tests for `solidity-extractor.js`
- Most of the apm refactors are similar, especially in how they begin, can something be abstracted from them?
- Unify conversions from ens-registry to `ensRegistryAddress` in scripts and tests, or remove the need for the conversion altogether ) -> **will be done on removing deprecated code PR**
- Improve how we handle`listr`context variables: [issue]https://github.com/aragonone/product/issues/222#issuecomment-548961338
- Don’t mutate the Listr context to communicate data between commands. Use command-scoped variables or find a substitute for Listr
- Tests have the same default values comment, they should all be /* Default values */

## After refactoring
- [ ] Move `/lib` to `typescript`. @dapplion have already been adding files that we can use first examples: [here](https://github.com/aragon/aragon-cli/blob/develop/packages/aragon-cli/src/lib/configEnvironment.ts), [here](https://github.com/aragon/aragon-cli/blob/develop/packages/aragon-cli/src/lib/typedef.js) and [here](https://github.com/aragon/aragon-cli/blob/develop/packages/aragon-cli/src/lib/acl/typedef.js).
- [ ] Add test on other parts of the codebase (e.g. utils)
- [ ] Windows CI
- [ ] CI for boilerplates, tutorials
- [ ] Full logic code test coverage.
- [ ] Implement analytics to know which commands are being used
- [ ] Move to Mocha + Chai for a better test framework: (better parsing, error handling, diff display)
- [ ] Flat commands and options objects (i.e. aragon dao token > aragon token, apm.ipfs > apm, ipfs)
- [ ] Stop consuming Solidity code and instead consume compiled ASTs. Perhaps we can bake in the antlr parser from federicobond, but it was also a big topic in the past to move to truffle 5 because we could stop doing the parsing ourselves
- [ ] Examples in CLI --help!

**Comment by macor161** [comment]
Great planning @0xGabi !

**Comment by 0xGabi** [comment]
We can consider this completed with the efforts on v7 and #1169
