### ISSUE TITLE
Refactor codebase for robustness (simplified)

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#981]
## 1. Logic / view refactor
- [x] 1.1 Extracts logic from dao commands #874 (@macor161 )
- [x] 1.2 Finish porting IPFS commands #951 (@0x6431346e )
- [x] 1.3 Move non development API objects in lib/ to its own package "toolkit".  (@0xGabi, @ajsantander )

## 2. Tests
- [x] 2.1 Move `e2e-tests` for commands to the `aragon-cli` package. This test will spin-up a chain and their entry-point are yargs commands. (@0xGabi, @0x6431346e  )
- [x] 2.2 Move `test` folder we currently have on the `aragon-cli` package to the new `toolkit` package. This test spin-up a chain and their entry-point is the new API. We should unify these tests without distinguish between unit or integration or e2e (@0xGabi )
- [x] 2.3 Move `e2e-tests` for `create-aragon-app` to its package. (@0xGabi , @0x6431346e  )
- [x] 2.4 Move away from unit tests, remove mocks. https://github.com/aragon/aragon-cli/pull/1026 (@ajsantander, @macor161   )
- [x] 2.5 Create documentation guides tests. (@ajsantander )
- [x] 2.6 Create new tests for create-aragon-app and templates. (@0x6431346e )
- [x] 2.7 Restore CI for aragon-cli. (@0x6431346e )
- [x] 2.8 CI for create-aragon-app. (@0x6431346e )
- [ ] :point_right: 2.9 CI for boilerplates. (@0x6431346e @0xGabi  ) PR: https://github.com/aragon/aragon-bare-boilerplate/pull/31
- [ ] (extra) :point_right: 2.10 Increase test coverage on the toolkit package (@0xGabi , @0x6431346e  ) PR: https://github.com/aragon/aragon-cli/pull/995
- [ ] (extra) :point_right: 2.11 Increase test coverage on the cli package (@0xGabi , @0x6431346e  ) PR: https://github.com/aragon/aragon-cli/pull/995
- [ ] 2.12 Make sure that no tests are skipped or onlyed (2nd pass)
- [x] 2.13 Finish moving tests from cli to toolkit (@ajsantander )
- [x] 2.14 Avoid manual linking of toolkit package in cli
- [x] 2.15 Automatic starting of devchain and ipfs on cli toolkit tests (@0x6431346e )

## 3. Misc
- [x] 3.1 Refactor deprecated code #946 (@0xGabi )
- [ ] (Nice to have) 3.2 Remove tiny dependencies #953 (@dapplion )
- [x] 3.3 Not using `process.exit()` Isuue: #948, PR: https://github.com/aragon/aragon-cli/pull/992 (@dapplion)
- [ ] (Nice to have) 3.4 Review deprecated `network` option and decide if makes sense to remove on this iteration.
- [ ] (Nice to have) 3.5 Centralize `Web3` and `aragonPM` on [configEnvironment](https://github.com/aragon/aragon-cli/blob/toolkit-package/packages/aragon-cli/src/lib/environment/configEnvironment.js) - Remove the need to use `Web3` object and the `ensureWeb3` [Here](https://github.com/aragon/aragon-cli/blob/toolkit-package/packages/aragon-cli/src/helpers/web3-fallback.js#L3) and [Here](https://github.com/aragon/aragon-cli/blob/toolkit-package/packages/aragon-cli/src/commands/run.js#L225)
- [x] 3.6 Fix snapshots, they're including personal paths
- [x] 3.7 Fix process.exit() on long standing commands PR: https://github.com/aragon/aragon-cli/pull/1032 (@dapplion )
- [ ] 3.8 Manual smoke testing with common usage scenarios (e.g. installing apps, assigning permissions, development workflows, etc.) : #1065 #1066
